language: java
jdk: oraclejdk8
sudo: required
services:
- docker
script:
- bash ./travis-deploy-docker.sh
deploy:
  provider: heroku
  api_key:
    secure: lmfhkZZWQ+IIFZGl5q3Y9p/DXxk69aMniGsa7F+TLbJyo7toaqzingHbPrjYPDQxBY53p7l119RF4BB/RuFBgmcn9IkaL3fNVig83s2gipKc21ze7DdOj6ku1ndZT5ciRqQxI+nKCME4CSjEshSE9xVt9Rybe7yRkFCqpB9v2CQ7AcuR4WTbQs/OEqiTFSI9VihH9+gSYklDM+UNUOK9n6D4VxnKokk2xzIU1CykLFxVT0YebJyZsyuPvgqQMY2kvNce7zHltER+udmNkSxgzn31V4xzNc9ZYvZtL3bkDcle4xpWONJKt1GG/PjieWyDJYAaZXszCvWR/KstArpN1dhClw+12KeVIXOh4ZbJgbctV+MI4hVxnnUocSg44h7gSmjkHXOptt5hDfM9OqktmhlqePsWsbzrxe+2RoIrqKFd2eVod9Luc8bWQz53P4DgTseYfHfz0QZSdEqWxc8Y+X4TKGMr/evzi6F+v/IRxl6INrQLXNNxUQhq3+uo5fCjw3+0FOXOlBcj7smvT0q9Txjrqn8HywKrDn3KSy/7w6CDzTSXOB2RNFAe9oxvKi6CfF3HMZzIPZKum+fwne+U6zZyH6EpjFzizBtURkaomyeG5fcdM5WyWw2PeiMypWDLG04w8fDp+R88AjCsX/clUy5Z+iXescinE9lJa0mzsEM=
  app: bopems-analyticsfiles
