language: java
jdk: oraclejdk8
sudo: required
services:
- docker
script:
- bash ./travis-deploy-docker.sh

after_success:
  # for local testing, needs to be set on travis, too:
  # export HEROKU_TOKEN=$(heroku auth:token)
- docker login --username=_ --password=$HEROKU_TOKEN registry.heroku.com
- docker tag $DOCKER_IMAGE_PROJECT/$DOCKER_IMAGE_NAME registry.heroku.com/$DOCKER_IMAGE_PROJECT-$DOCKER_IMAGE_NAME/web
- docker push registry.heroku.com/$DOCKER_IMAGE_PROJECT-$DOCKER_IMAGE_NAME/web
- heroku container:push web -a $DOCKER_IMAGE_PROJECT-$DOCKER_IMAGE_NAME
- heroku container:release web -a $DOCKER_IMAGE_PROJECT-$DOCKER_IMAGE_NAME