language: java
jdk: oraclejdk8

# WhiteList
branches:
  only:
  - master

sudo: required

services:
- docker

after_success:
- docker login -u $DOCKER_USERNAME_LOGIN -p $DOCKER_PASSWORD
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
- export IMAGE_NAME=$DOCKER_USERNAME_BOPEMS/analyticsfiles
- docker images
- docker build -t $IMAGE_NAME:$TRAVIS_COMMIT .
- docker tag $IMAGE_NAME:$TRAVIS_COMMIT $IMAGE_NAME:$TAG
- docker images
- docker push $IMAGE_NAME